In [2]:
import torch
import time
import numpy as np
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00110745


In [4]:
torch_rand1 = torch.rand(1000,1000).to(device)
torch_rand2 = torch.rand(1000,1000).to(device)

np_rand1 = torch.rand(1000,1000)
np_rand2 = torch.rand(1000,1000)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.03588629
0.00997376


In [5]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [6]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [7]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [8]:
print(torch.exp(out))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [9]:
tensor1= torch.tensor([1,2,3])
tensor2= torch.tensor([4,5,6])
tensor3= torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([ 5.4932, -2.1483,  4.5143], grad_fn=<SqueezeBackward4>)


In [11]:
import torch.nn.functional as F
tensor1= torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [12]:
import torch
import torch.nn as nn

# Define the size of the vocabulary and the dimensionality of word embeddings
vocab_size = 1000
embedding_dim = 300

# Create an embedding layer
embedding_layer = nn.Embedding(vocab_size, embedding_dim)

# Input tensor representing word indices
input_indices = torch.LongTensor([[1, 2, 3], [4, 5, 6]])

# Pass the input tensor through the embedding layer to get word embeddings
embeddings = embedding_layer(input_indices)

print(embeddings.shape)  # Output: torch.Size([2, 3, 300])


torch.Size([2, 3, 300])
